### ISSUE TITLE
The Broadcast function is exported but not usable outside of the package

### ISSUE THREAD

**Issue by owulveryck** [gorgonia/gorgonia#223]
I need to implement a "add" operator for two tensors with a broadcasting mechanism as described [here](https://github.com/onnx/onnx/blob/master/docs/Broadcasting.md).

The [`Broadcast`](https://godoc.org/gorgonia.org/gorgonia#Broadcast) function seems to be a perfect fit for this. Moreover, the [test](https://github.com/gorgonia/gorgonia/blob/master/broadcast_test.go#L56) is partially implementing what I am trying to do.
But nor the `ʘBinaryOperatorType` or any other `binOp` implementations are exported.

Therefore the Broadcast function can only be used within the Gorgonia package.

Maybe we should make it private to avoid confusion in the documentation and expose "Broadcasted version" of some operators instead? What do you think?

**Comment by chewxy** [comment]
I had a look at `Broadcast` - hadn't touched it in years. That and the elementwise operations should be hung in the Shitty Software Engineering Hall of Fame. Will get in contact with you to work on this further.

**Comment by chewxy** [comment]
https://github.com/gorgonia/gorgonia/releases/tag/v0.9.0-beta < -- this is out so your PR can be based off this

**Comment by deasmhumnha** [comment]
Trying to implement a column-wise normalization and running into the same problem. I don't feel I have enough of an understanding of `gorgonia` yet to attempt a PR, but I am curious about the design choice of requiring an explicit broadcasting pattern rather than having an implicit set of rules that act on  ndarrays based on their shapes (as Numpy does).

**Comment by chewxy** [comment]
I put it to you that having implicit broadcasting leads to subtle errors you may not have caught. Even when you are familiar with the rules.

The rule is quite simple: a lower dimensioned tensor is an embedding within the higher dimension tensor.  Easy to state, but not easy to remember when working on complicated things. Having an explicit broadcast meant that you know exactly where the broadcast happens in code.

As for not making it  usable (the function is exported, the op isn't)... that's really more of a technical issue. I believe at one point the circle with a dot was considered exported. Or I may be wrong.

**Comment by deasmhumnha** [comment]
I figured that was the primary motivation. It's a code clarity vs. code complexity trade-off for sure. Also, as owulveryck mentioned, wouldn't you also have to export the various lowercase implementations as well? It would also be nice if you could broadcast a custom `BinaryOp`.

**Comment by chewxy** [comment]
Send PR! :)  (you seem to be aware of the `BinaryOp` type)

**Comment by chewxy** [comment]
oh I just realized you're not @owulveryck

**Comment by deasmhumnha** [comment]
I can definitely try! I'm slowly becoming familar with the library. First I'm going to try to implement some of the special functions in `math` as `Op`.

**Comment by chewxy** [comment]
Be sure to implement them as `ADOp` and `SDOp` as well. `ADOp` plays nice with the lispmachine, giving you autodifferentiation, SDOp place nice with the compiled machines (*tapeMachine, ccsMachine, etc)

**Comment by owulveryck** [comment]
I have though about it. I really like the idea of gorgonia being as close as possible of the arithmetic and therefore leaving the broadcasting function apart.
But the more I work with it, the more I realize it can be tricky to use. 
I still haven’t found any elegant solution. 
I’d like something usable like:

Add(a, broadcast(b, broadcastPattern))

**Comment by chewxy** [comment]
> I really like the idea of gorgonia being as close as possible of the arithmetic and therefore leaving the broadcasting function apart.

Broadcasting is actually technically part of the arithmetics. If `a` and `b` are (2,3) and (3)-shaped tensors , then technically `a + b` is defined (that is to say, we assume `b` is an embedding in the tensorspace of `a`)

The problem is in programming. Implicit broadcasting causes errors. Sometimes, these errors are very subtle - the system does not report an error, because it's technically correct, and as a result your neural network becomes silly.

There is a solution - the longer term thing I'm working on :P - better type systems to constraint these sorts of problems. If you trawl through the code, you may see [scars of previous attempts](https://github.com/gorgonia/gorgonia/blob/master/type.go#L45).

In the past I had sketched through some solutions. I have some solutions I know works, but are not suitable for production use. For example, if we were to go down the dependent types path, then a new calculus is required. If we were to go down the refinement types path then a SAT solver is required. There are also some other esoteric calculi out there that handles these sorts of situations well, but those are not well trod paths and would possibly have performance issues.

As such I eventually left the type system as a frankenstein simply-typed system with some amount of HM inference. 

# The Problem In General #

The problem can be described as such: 

Choose the type of function signatures of `Add`:

```
Add : a -> a -> a
Add (a => SomeRing) : a -> a -> a
```

Any type signature of `Add` has to pass the following tests. The notation is a bit complicated, but I wanted to show the input types of the arguments. `Add(a, b (2,3)-Tensor)` can be read as call `Add` on `a` and `b`, both of which are the `Tensor` type, and has a shape of `(2,3)`. The `->` shows the type returned.

* `Add(a, b (2,3)-Tensor) -> (2,3)-Tensor`
* `Add(a (2,3)-Tensor, b Scalar) -> (2,3)-Tensor`
* `Add(a Scalar, b (2,3)-Tensor) -> (2,3)-Tensor`
* `Add(a, b Scalar) -> Scalar`
* `Add(a (2,3)-Tensor, b (3)-Tensor) -> (2,3)-Tensor`
* `Add(a (3)-Tensor, b (2,3)-Tensor) -> (2,3)-Tensor`

And it should fail/error in these situations:

* `Add(a (2,3)-Tensor, b (3,2)-Tensor) -> error `
* `Add(a (3,2)-Tensor, b (2,3)-Tensor) -> error `
* `Add(a (2,3)-Tensor, b (6)-Tensor) -> error `
* `Add(a (2,3)-Tensor, b (2)-Tensor) -> error `

Of particular interest may be `Add(a (2,3)-Tensor, b (6)-Tensor)`. In what world could anyone possibly do this? My answer to that is once you allow reshape operations into a mathematical system, to many people, a (2,3)-Tensor and a (6)-Tensor are the same... the discipline goes away.  This obviously comes from real life experience of dealing with other people's code 😝.

# How Does This Relate to Broadcast? #

An ideal situation would remove `Broadcast` - let the underlying calculi of types handle the situations. Unfortunately due to the crappy type system that Gorgonia has, this cannot currently be done without careful analysis of programs.

# What Is To Be Done? #

I don't particularly know. I keep experimenting with ideas. I hope others do so too.

**Comment by chewxy** [comment]
@owulveryck 

> This would not break the API, but this is not possible

APIs CAN break. Please do design a system that breaks API if necessary.

**Comment by deasmhumnha** [comment]
@owulveryck 
> Add(a, broadcast(b, broadcastPattern))

To work correctly, the broadcasting function needs to know about both `a` and `b`. So either both need to be passed to a one-shot function or broadcasting becomes a two-step process: first a function to figure out the broadcast shape for `a` and `b` and then a function to broadcast either/both to this new shape. This would be like using a `broadcast` object to get the shape and then `broadcast_to` to resize in NumPy. The good thing about this route is that it separates broadcasting from the operation itself, so that none of the currently private types or instances need to be exported and it will work with any custom `Op` as well.

**Comment by owulveryck** [comment]
Thanks for all the explanation @chewxy!
This is very helpful.

I propose a new API which is "semi-manual" for now. My understanding is that broadcasting only applies to `binOps`, so I have changed all the implementation to take the `broadcastPattern` as the third argument.

It does not _let the underlying calculi of types handle the situations_, but it is sufficient to close this Issue while waiting for a better implementation.

I will practice with it and see if I find a better solution. WDYT?

**Comment by owulveryck** [comment]
About the broadcast function, I think that we don't need to pass the `binaryOp` as argument.
What I propose is to use a function that takes two input nodes and a pattern and that returns two nodes. 
Under the hood, the function modify the graph (what it does at the present time), but at the end it does not apply the operator.

```go
// Broadcast apply the pattern to the input nodes
// and returns two nodes suitable for a binary operator.
// Broadcast works somewhat like Numpy's broadcast, except it's now exposed as a function.
func Broadcast(a, b *Node, pattern BroadcastPattern) (*Node, *Node, error)
```

Then to use it:
```go
g = NewGraph()
x = NewMatrix(g, Float64, WithShape(2, 3), WithValue(xT), WithName("x"))
y = NewVector(g, Float64, WithShape(2), WithValue(yT), WithName("y"))
if a, b, err = Broadcast(y, x, NewBroadcastPattern([]byte{1}, nil)); err != nil {
        ioutil.WriteFile("Broadcast.dot", []byte(g.ToDot()), 0644)
        t.Fatalf("%+v", err)
}
z, err = Add(a, b)
if a, b, err = Broadcast(x, y, NewBroadcastPattern(nil, []byte{1})); err != nil {
        ioutil.WriteFile("Broadcast.dot", []byte(g.ToDot()), 0644)
        t.Fatal(err)
}
```

I have created a [branch](https://github.com/gorgonia/gorgonia/tree/broadcast-elements) for this. The tests are passing, but I think it needs more tests.
