### ISSUE TITLE
the latest gonum library using Nodes instead of []Node

### ISSUE THREAD

**Issue by godshen** [gorgonia/gorgonia#237]
..\github.com\chewxy\gorgonia\walker.go:43:43: cannot use g (type *ExprGraph) as type graph.Directed in argument to topo.SortStabilized:
        *ExprGraph does not implement graph.Directed (wrong type for From method)
                have From(int64) []graph.Node
                want From(int64) graph.Nodes

**Comment by owulveryck** [comment]
I have created a branch [ìssue-237`](https://github.com/gorgonia/gorgonia/tree/issue-237) and tried to implement the new interface of gonum.

Not all the tests are green (concurrent training is failing and I didn't investigate to see if it is due to my modifications).
I do not assign the ticket to myself because I won't have more time to work on it by now.

**Comment by godshen** [comment]
> Gonum is now using an Iterator. Gorgonia should be modified to use (or implement) this interface.
> 
> I have created a branch [`issue-237`](https://github.com/gorgonia/gorgonia/tree/issue-237). I am using one of the implementations provided by Gonum within the Iterator package.
> 
> Not all the tests are green (concurrent training is failing, and I didn't investigate to see if it is due to my modifications).
> This is why I do submit a PR




Thanks Very Much

I am afraid to modify the library because I found that there are lots of related code
So I do "git reset --hard commit OldID" to use old []Node make it successful run
Waiting for your next released version adapting these change
