### ISSUE TITLE
gorgonia can not be build with go1.13

### ISSUE THREAD

**Issue by blackrez** [gorgonia/gorgonia#305]
When I try to build gorgonia with go1.13, I have this error : 
```
go: gorgonia.org/gorgonia@v0.0.0-20190629120756-e8196037ec06: unrecognized import path "gorgonia.org/gorgonia" (https fetch: Get http://gorgonia.org/gorgonia/?go-get=1: redirected from secure URL https://gorgonia.org/gorgonia?go-get=1 to insecure URL http://gorgonia.org/gorgonia/?go-get=1)
```

I can build it with go get -insecure 

@chewxy found the issue is linked to https://github.com/isaacs/github/issues/289

**Comment by owulveryck** [comment]
I think that this issue can be fixed by enforcing https on github pages.

Sadly, I do not want to activate the option because of this error message:

<img width="740" alt="Screenshot 2019-08-21 at 17 13 17" src="https://user-images.githubusercontent.com/11583401/63444552-1bca5100-c437-11e9-8856-ccd7995380c1.png">

I just sent an email to the GitHub "support" to ask for some information about the issue here.
I will keep this issue updated once I have more news.

**Comment by owulveryck** [comment]
I had an answer from GitHub; We are doing DNS actions that may take 72 hours to propagate.

**Comment by owulveryck** [comment]
It is now ok after some changes in the DNS record and GitHub pages settings.

```
➜  GOROOT=/tmp/go GOPATH=/tmp/tmpggn /tmp/go/bin/go version
go version go1.13rc1 darwin/amd64
➜  GOROOT=/tmp/go GOPATH=/tmp/tmpggn /tmp/go/bin/go get gorgonia.org/gorgonia && echo ok || ecko ko
ok
```

**Comment by deadprogram** [comment]
What were the changes you had to make? I am having this same problem on gobot.io
