### ISSUE TITLE
Enhance the goreport card

### ISSUE THREAD

**Issue by owulveryck** [gorgonia/gorgonia#328]
Do whatever fix that increases the [go-report](https://goreportcard.com/report/gorgonia.org/gorgonia)

Results at the creation of this issue:

|  analysis | score |
| ------------- | ------------- |
| gofmt   |   99% |
| go_vet | 100% |
| golint | 91% |
| gocyclo | 78% |
| ineffassign | 97% |
| license | 100% | 
| misspell | 99% |

**Comment by volmedo** [comment]
I'll have a look at this :)

**Comment by volmedo** [comment]
I opened a PR that bumps ineffassign score to 100%.

Please check changes carefully since I just did what it was required for ineffassign to not complain, but some cases really look like issues in the code.

I also had a look at misspell warnings, but they are actually false positives. I checked whether there is a way to make misspell ignore them (such as using special comments in the source code) but I found nothing.
