### ISSUE TITLE
How to implement embedding layer?

### ISSUE THREAD

**Issue by zhenghaoz** [gorgonia/gorgonia#403]
Hi, I'm going to implement neural collaborative filtering using gorgonia. However, when I read CharRNN in examples to learn how to implement embedding layers, I find its implementation is quite complex. It seems inefficient since the graph will be modified over time. Will there be "Embedding Layer" in the future? :smile:

**Comment by chewxy** [comment]
An embedding layer is essentially a matrix of shape `(n, dim)`.  So, if you have 1000 "words" (could be any discrete option - users, etc etc), and you want an embedding dimension of 50, you simply create a `*Node` with shape `(1000, 50)`:

```
g := NewGraph()
emb := G.NewMatrix(g, G.Float64, G.WithShape(1000, 50), G.WithInit(GlorotN(1)), G.WithName("embedding"))
```

Now, each row in `emb` represents one "word". This of course, implies that you need to have your words stored with its associated ID. A simple `map` usually does the trick:

```
m := map[string]int{ "-UNK-": 0, "hello": 1, "world": 2 }
```

To use the `emb`, simply select a row. This is done with `Slice`.

Say you want to get the embedding for the word "hello":

```
hello, err := G.Slice(emb, G.Slice(G.S(m["hello"])))
```

Here we see `hello` is a `*Node` that holds the slice. `G.S` is the function to create the slicing range (in this case, it is equivalent to `emb[1:2]` ).

But how do you do this dynamically?

Well, `UnsafeLet` has special checks for these sorts of thing. But for now, let's write a sample program:

```
g := NewGraph()
m := map[string]int{ "-UNK-": 0, "hello": 1, "world": 2 }
emb := G.NewMatrix(g, G.Float64, G.WithShape(len(m), 50), G.WithInit(GlorotN(1)), G.WithName("embedding"))
x, err := G.Slice(emb, G.Slice(G.S(m["-UNK-"])))
// check err
// use `x`

vm := G.NewTapeMachine(g)
for _, id := range m {
    G.UnsafeLet(x, G.S(id)) 
    vm.RunAll()
    // do things
    vm.Reset()
}
```

Now, there are specialized usefulness from libraries like [`lingo/corpus`](https://github.com/chewxy/lingo), which would be used instead of a plain `map`. But in general, that's all you need.

**Comment by chewxy** [comment]
The main reason for not adding an embedding layer in Golgi was because while a `map` is useful for a large number of cases, there are times you might want a more specialized data structure (such as a `*corpus.Corpus`)

**Comment by chewxy** [comment]
If I were to implement it as a `golgi.Layer`, I'd do something like this: 

```
type Embedding struct {
    lookup map[string]int
    W *gorgonia.Node
}

func (e *Embedding) UnsafeLet(id int) { gorgonia.UnsafeLet(e.W, gorgonia.S(id))} 
```

**Comment by zhenghaoz** [comment]
Thank you so much :smile:. I'll try it.
